// Illustrative numbers for the marketing pages only. Signed-in screens render
// real data or an empty state, never these.
import type { FundOverlap, Investment, StockExposure } from "@/lib/api/types";
import { currencyForCountry } from "@/lib/finance/currency";

function demoSecurity(
  id: string,
  name: string,
  ticker: string,
  country: "IN" | "US",
): StockExposure["security"] {
  return {
    id,
    userId: "demo",
    standardizedName: name,
    ticker,
    country,
    currency: currencyForCountry(country),
  };
}

export const placeholderExposures: StockExposure[] = [
  {
    security: demoSecurity("demo-hdfc", "HDFC Bank", "HDFCBANK", "IN"),
    mutualFundInvestedInr: 180000,
    etfInvestedInr: 42000,
    directInvestedInr: 0,
    indiaInvestedInr: 222000,
    usInvestedInr: 0,
    totalInvestedInr: 222000,
    portfolioPercentage: 18.4,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-aapl", "Apple", "AAPL", "US"),
    mutualFundInvestedInr: 95000,
    etfInvestedInr: 70000,
    directInvestedInr: 40000,
    indiaInvestedInr: 0,
    usInvestedInr: 205000,
    totalInvestedInr: 205000,
    portfolioPercentage: 17,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-rel", "Reliance Industries", "RELIANCE", "IN"),
    mutualFundInvestedInr: 60000,
    etfInvestedInr: 38000,
    directInvestedInr: 70000,
    indiaInvestedInr: 168000,
    usInvestedInr: 0,
    totalInvestedInr: 168000,
    portfolioPercentage: 13.9,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-msft", "Microsoft", "MSFT", "US"),
    mutualFundInvestedInr: 52000,
    etfInvestedInr: 61000,
    directInvestedInr: 0,
    indiaInvestedInr: 0,
    usInvestedInr: 113000,
    totalInvestedInr: 113000,
    portfolioPercentage: 9.4,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-nvda", "NVIDIA", "NVDA", "US"),
    mutualFundInvestedInr: 28000,
    etfInvestedInr: 54000,
    directInvestedInr: 22000,
    indiaInvestedInr: 0,
    usInvestedInr: 104000,
    totalInvestedInr: 104000,
    portfolioPercentage: 8.6,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-infy", "Infosys", "INFY", "IN"),
    mutualFundInvestedInr: 48000,
    etfInvestedInr: 21000,
    directInvestedInr: 0,
    indiaInvestedInr: 69000,
    usInvestedInr: 0,
    totalInvestedInr: 69000,
    portfolioPercentage: 5.7,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-amzn", "Amazon", "AMZN", "US"),
    mutualFundInvestedInr: 18000,
    etfInvestedInr: 41000,
    directInvestedInr: 0,
    indiaInvestedInr: 0,
    usInvestedInr: 59000,
    totalInvestedInr: 59000,
    portfolioPercentage: 4.9,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-tcs", "TCS", "TCS", "IN"),
    mutualFundInvestedInr: 31000,
    etfInvestedInr: 12000,
    directInvestedInr: 15000,
    indiaInvestedInr: 58000,
    usInvestedInr: 0,
    totalInvestedInr: 58000,
    portfolioPercentage: 4.8,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-googl", "Alphabet", "GOOGL", "US"),
    mutualFundInvestedInr: 12000,
    etfInvestedInr: 36000,
    directInvestedInr: 0,
    indiaInvestedInr: 0,
    usInvestedInr: 48000,
    totalInvestedInr: 48000,
    portfolioPercentage: 4.0,
    breakdown: [],
  },
  {
    security: demoSecurity("demo-meta", "Meta", "META", "US"),
    mutualFundInvestedInr: 8000,
    etfInvestedInr: 27000,
    directInvestedInr: 9000,
    indiaInvestedInr: 0,
    usInvestedInr: 44000,
    totalInvestedInr: 44000,
    portfolioPercentage: 3.6,
    breakdown: [],
  },
];

export const placeholderInvestments: Array<Pick<Investment, "id" | "name" | "type" | "country" | "currency"> & { invested: string; lastSync: string }> = [
  { id: "pi-1", name: "Bandhan Small Cap Fund Direct Growth", type: "mutual_fund", country: "IN", currency: "INR", invested: "₹12,40,000", lastSync: "12 Aug 2026" },
  { id: "pi-2", name: "Nippon India Nifty 50 ETF", type: "etf", country: "IN", currency: "INR", invested: "₹3,80,000", lastSync: "12 Aug 2026" },
  { id: "pi-3", name: "Parag Parikh Flexi Cap Direct", type: "mutual_fund", country: "IN", currency: "INR", invested: "₹6,10,000", lastSync: "3 Jul 2026" },
  { id: "pi-4", name: "Invesco QQQ", type: "etf", country: "US", currency: "USD", invested: "$8,400", lastSync: "12 Aug 2026" },
];

export const placeholderOverlaps: FundOverlap[] = [
  {
    fundAId: "pa",
    fundAName: "Parag Parikh Flexi Cap",
    fundBId: "qqq",
    fundBName: "Invesco QQQ",
    overlapScore: 12.4,
    overlappingSecurities: [
      { securityId: "msft", name: "Microsoft", ticker: "MSFT", allocationA: 5.0, allocationB: 8.1 },
      { securityId: "amzn", name: "Amazon", ticker: "AMZN", allocationA: 5.5, allocationB: 5.2 },
      { securityId: "aapl", name: "Apple", ticker: "AAPL", allocationA: 2.1, allocationB: 8.8 },
      { securityId: "nvda", name: "NVIDIA", ticker: "NVDA", allocationA: 1.8, allocationB: 8.4 },
      { securityId: "googl", name: "Alphabet", ticker: "GOOGL", allocationA: 2.4, allocationB: 5.1 },
    ],
  },
  {
    fundAId: "bandhan",
    fundAName: "Bandhan Small Cap",
    fundBId: "nifty",
    fundBName: "Nifty 50 ETF",
    overlapScore: 6.8,
    overlappingSecurities: [
      { securityId: "hdfc", name: "HDFC Bank", ticker: "HDFCBANK", allocationA: 2.2, allocationB: 11.4 },
      { securityId: "icici", name: "ICICI Bank", ticker: "ICICIBANK", allocationA: 1.4, allocationB: 7.9 },
      { securityId: "infy", name: "Infosys", ticker: "INFY", allocationA: 1.1, allocationB: 5.6 },
      { securityId: "rel", name: "Reliance Industries", ticker: "RELIANCE", allocationA: 0.9, allocationB: 8.2 },
    ],
  },
];
